name: sistema_almacenes
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_barcode_scanner: ^2.0.0
  http: ^1.2.1
  flutter_login: ^5.0.0
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/layout.png
    - assets/ggg.gif
    - assets/lo.gif
    - assets/lapiz.gif
    - assets/icon.png
 
